### ISSUE TITLE
Could you post a tutorial video or article

### ISSUE THREAD

**Issue by zengxpmaster** [Andy-K-Sparklight/Alicorn#130]
- [ ] **Could you post a tutorial video or article on how to install Alicorn on ARM64 devices**

I can't install this launcher on my raspberry. 
I did my best to deal with the dependencies such yarn Node.js , but I failed.

Can you upload it to Bilibili if possible?

**Comment by Andy-K-Sparklight** [comment]
Support for ARM is only at a very early stage and **probably** won't work as expected (since there are no corresponding native libraries for JInput which Mojang used).
I do not have an ARM device, so testing this will take time.
And, if you may, I'd like you to describe your installation in detail. This will help us to resolve the problem.

**Comment by Andy-K-Sparklight** [comment]
See also #135

**Comment by skjsjhb** [comment]
您好。
抱歉没有及时回复。
Alicorn 的原始开发者已经离开社区，Alicorn 现在由我负责必要的维护工作。
有关您的 Issue，Mojang 现已提供 arm 的官方支持，Alicorn 所提供的兼容库已经过时，不再需要。
这个 Issue 将被关闭，如果有追加问题，您可以再创建一个 Issue。
