### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by DearJasker** [Andy-K-Sparklight/Alicorn#31]
1.The initialization process failed to close the launcher
2.The upper right corner of the Java selection window still allows you to re-enter this page
3.Translation should be more in line with the actual usage habits, but not use some proper nouns used by developers.Such as using “存储位置” not “容器”.(I may use a pull request later to modify the translation)
4.The directory selection box shall allow direct editing.
5.Almost all animations in windows are lagging.
6.GC1 and GC2 shall not be allowed to be repeated, otherwise it may be unable to start
7.InstallForge and InstallFabric maybe can be merged into one button
8.Optifine version not recognized

┗(•ω•;)┛

**Comment by DearJasker** [comment]
You should thank meO(∩_∩)O

**Comment by Andy-K-Sparklight** [comment]
1. Not able to Represent, probably because close function isn't ready at that time, or Electron are running some renderer tasks which might block the close signal.
2. Designed as this.
3. The language style of PonyCN isn't specially designed for newbies, I'll write a new style for them soon.
4. Fixed.
5. Performance improved, while this mostly depends on your GPU, Alicorn's operations make little difference.
6. It's not really necessary, newbies should never change this option, while experts should know that they cannot choose the same one - but I'll prepare a solution for this.
7. Considered that OptiFine install will soon be supported, I might just seperate them into multiple pages, since some helps will be placed at the blank place.
8. Fixed, and thanks for letting me have a chance to improve the awful args generator ;)

And please, next time, **seperate different suggestions into different issues**, it will be easier for me to link commits with them (and interact with GitHub), there can never be too many issues.

Thanks after all!

**Comment by DearJasker** [comment]
Thanks!
Have a good time.



At 2021-08-30 10:43:56, "Andy K Rarity Sparklight" ***@***.***> wrote:

Not able to Represent, probably because close function isn't ready at that time, or Electron are running some renderer tasks which might block the close signal.
Designed as this.
The language style of PonyCN isn't specially designed for newbies, I'll write a new style for them soon.
Fixed.
Performance improved, while this mostly depends on your GPU, Alicorn's operations make little difference.
It's not really necessary, newbies should never change this option, while experts should know that they cannot choose the same one - but I'll prepare a solution for this.
Considered that OptiFine install will soon be supported, I might just seperate them into multiple pages, since some helps will be placed at the blank place.
Fixed, and thanks for letting me have a chance to improve the awful args generator ;)

And please, next time, seperate different suggestions in different issues, it will be easier for me to link commits with them (and interact with GitHub), there can never be too many issues.

Thanks after all!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
